services:
  app:
    build: .
    ports:
      - "7777:7777"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=tvseries_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
